apiVersion: v1
kind: ServiceAccount
metadata:
  name: truehear-backend
  namespace: backend
  labels:
    app.kubernetes.io/name: truehear-backend
    app.kubernetes.io/part-of: truehear-platform
automountServiceAccountToken: false
