apiVersion: v1
kind: Secret
metadata:
    name: flux-pull-secret
    namespace: default
type: addons.cluster.x-k8s.io/resource-set
stringData:
    flux-github-pat.yaml: ENC[AES256_GCM,data:2AqfU6YIcPoCcuMMLBxTYxgjAiwbAvT1jMW1XZK1kPYgywDVUPWzKqjq0ZJYrbf0lNmdLL1+CGOm7DRfBNZ08Jx+Hc82w43Y+oAGlkhjZN0/HUacR2U+n0zOpg8aU72zPJqO80a5W6FeE6cYDfiT49Q0zCVshkGAw6PcOPC6Fm7cOakU6OVeZV+s3UylA4niObVPxg3jeAkNFqpjkbn6GcsR8IuAxnYlNBK2GD7thooRO3a++Lyokyjh21KmbFlBiUxivAwrvsOC7T1+EkAPv31a1ON6lesrz2N69Cx7USIZ0svFKUAysrQ=,iv:NYGSADGVw9qVjXildETudLBAqbOhUYX5oHr40bluDMA=,tag:Bg8dqBzVm5pQhEuRoU4eOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZGVCWG1TUm9KNE9NY2pp
            WTFiVlZLY3pVUk5tZzhUQlJ3M3Z3blV6V1ZnCmJLMTluRTFmUkJ1eTdGNHVjSnpN
            RnNnQ0x4VlMyK0RETitySlFIa2pIZFkKLS0tIDdXSG8ycytUNTBxUi95VTdyc0lD
            Q0tUaW9QUEtST1NMWkRFL0UxbGV6bncKJy81bHS6Z/xZNWe0f+YB2J+eFPk9dXvi
            Ro3VmSgS6VugjfMOGroyeP7YE4jzSAdsDd2JRjmbNi5jT+Waq4jAbg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qdn86vl3v58juv4j7gwuz3qu9hjl4fhcpvla39m848cgz3xd44asxa30nv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T07:41:15Z"
    mac: ENC[AES256_GCM,data:wKRLkjLFjBn+qSkItquZqHNYLl9qxemws3423Dei+9WRTuwosL+yOHpCDoCDNz8mXIMgN+yr/DyzG1qr8kPf+BYphyWzQuf6wsixbfi8OksdARURHtf+2bP7d6Xr7Hh6v733YSZY2yy7sGQCxNG0CI2Jo3UQT2PrwWGqItKNlJA=,iv:9n8KoaVC8LH+IPlUrROvMhMhJXhxmksx60c/EiZnnyU=,tag:6kJYnTFOuL3uOuOCVe93qA==,type:str]
    version: 3.13.2
