apiVersion: v1
kind: Secret
metadata:
    name: flux-pull-secret
    namespace: default
type: addons.cluster.x-k8s.io/resource-set
stringData:
    flux-github-pat.yaml: ENC[AES256_GCM,data:I54geoGUutbrDbz02cxvV7f05jyp8AskfCqb4V47R9EBczib03QBCwyDJls3vOoFClM0+Cd0Zs5zX0rC1HGLtzsSEKZbfpqIfrNQE90CN12+3D5gAbnzj95zSB4PZ6HboeILmhj4cMv3dfANvPKu2t4FeqUtYJ87gIrn1+18mL4zbWvA3HvwnmsAwROMbk5py9/71sSg+c9eTByA487VndAMLaBXuFWqR4mzVlEj4WDdNim4Vxh10Zwv6eJsRLxhUUS6zSbHIer8Ha1iFfayeQ8PWkbCvoVpbJh+OBi1Kbx+w8W4Pxp6v10=,iv:A4xUMyaolaBqo/ry6daA1al/gKToGjIjzr533iItwUA=,tag:1FVV8DSyZmxgsl51jIBJog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRlV5ZnJYV1JIVEpKNXEz
            K3NPaXVtZlhnSEpFSXM5dHluS2Y5NmtxUHk4CjRxenNJWCtOaEovUHlBQUlLUlRK
            YTBsS1IyUVB3MENQNnQ4Ukd5dW84R3MKLS0tIFVSUlprcUh0WnMwdzljVDEwWkFV
            REszajE4bzQrQ2wvbE5SK0luMnJwMEUKCMujyoq+0qQctjj2obscIMNo3Dr4sTiL
            vWn2sdPeG40IlEEStKJ5DhrMUc49mwE66EN0igq5+Kg4QX3pxtlvag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qdn86vl3v58juv4j7gwuz3qu9hjl4fhcpvla39m848cgz3xd44asxa30nv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T12:50:32Z"
    mac: ENC[AES256_GCM,data:Xc4DX7cdfjnfao1qjVwbQY7Phv4p7+IXR4fBKGudJslRIeeYFJd6oK1/vzljRIXVDd09rEAf1SVa5gJ3/NXuA9rHL8whAzSZcOnuEslA2afM0S+OGOdyDewZ6CSgZwNKwn6z9a8RG2GnAQWl4xQtcf4m93tFwsd9WXOk3jNLB/I=,iv:KZFvfCIiLdri9EAxaEulO0Rb64xLhqe8gfOmvT4SeQs=,tag:6DEvEGMWuyYiyXLIFPQYcA==,type:str]
    version: 3.13.3
