apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: capa-system
type: Opaque
stringData:
    AWS_B64ENCODED_CREDENTIALS: ENC[AES256_GCM,data:/Lpl6m5Kx+t9wQZxS3UdDgUJbc2VnCXLe9GnCRLvN8GTCuMC0EUZwaFhE4mkplSDo6PVii9zFl/5ZGv9ddrXOBj2aIdUiMNNgMfiA33nb8IMYHIs2ptWrfNMzNliV4D4Oui6ujBxmK32iAHReZ7RM6fUsX5Rraxo99Dr8UU4b2ctcuARs5vcbPm8ds+cPerl3CTLjDya2duwXZEKeiPTiJTQe1bWorNXdlLOsnw+ALOCZujZcs+15g==,iv:RbzDMXyi0RcJpBR+WuEbfpHYLAWiS+iDGHZ49tKr27s=,tag:qLkMjgefzd3hDNRczAOq5g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc1Z5R0tvU3h4ZSs3d29U
            ZEhZTGtvclBQek1PMVRnc2RKTmd3dFM5bFY0CnRNNFlQMDJsaTk2US9lcGNWZG41
            aDFBRk9HUXVzRGVLQ3dpTVBJR2wraWcKLS0tIHh1T0d3YXhzMXNWV3dHZi9GWUJw
            YjBJd0U0bWZuK0tTNUZONHlyTDBiN28KieYC9Y4emHLZaVyB5lV9QIrHcw+YVxX+
            rZngqqYlm8DujOaSzcASGpjd2u55fnAc7XmbNnUkkTZOzSqE0IoZ8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qdn86vl3v58juv4j7gwuz3qu9hjl4fhcpvla39m848cgz3xd44asxa30nv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T17:19:10Z"
    mac: ENC[AES256_GCM,data:pOaBHvPMECcLFYLWcetjsP8sJFvMTxBXUktv8Z82ML3ftKndM26SUv6XuxqYn6M5bErMQtktnNY04J9+uh+juOeM3ASyVO6pEiQwDblC38hdPXJjf91iwcBEBiFaop6VmHKcCqLiUoZMIxz+FkUNvNaXOyx/5+//8FjEmSy7IT8=,iv:pHS+Ielh5AyR7nkGYrcphxe0Z8anVx9uqNj9oEeBvII=,tag:xNu2XH+SHY08RgXch5M2zg==,type:str]
    version: 3.13.3
