apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: capa-system
type: Opaque
stringData:
    AWS_B64ENCODED_CREDENTIALS: ENC[AES256_GCM,data:DxU12f7guyntFSwGCRavp/nE17dduUlbHVzWKOAsIGHy2a5K+03mH5iNRrsYV1N+78WPN23XQT0jBDoUFiRye7mVzS2A+WR+Ls9JhCuIW/aBmTm2V8VT79Y8IjDMMebyxggmEzZsQM9mlTQmizV32DQLu9zuiv/gt8wo83oUZqL3psqkZSxvzh1o0GN0f41LN+8RUVnQOvoRhpY7l916O8IIuGo6uHGsBoTIpaTZsGnPEvvZM0OGZQ==,iv:BWtMb9dcgUg1w4QIuaSNUFG679CwI4YpsZqsebmL4wY=,tag:Tzqtga6go9nPF8z5t3ctsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OGhnTERtUEtFMnN0bmF2
            Sys1dEpNbk5yK3lYRFliNUFHTHVZMGJlRVQ0CkN4R2Y2T3V6dFlucmhXeUc5Wm16
            QVNaR2p3bTlIWE02NHlncWNFWmRhajQKLS0tIG9IRVZKYXVsNE1HS0R4cDZXeUxW
            c2FUYkFjaitjTHgxcFZZQ1dQZVdCdFkKNz3gERejDkBCorIvLfJY2bBZ9xFDddIZ
            5ozhMk0SLKBBIWSzXZtDGSc+o4R0IwMhZKGpDeWbbZA5MngC24y4Uw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qdn86vl3v58juv4j7gwuz3qu9hjl4fhcpvla39m848cgz3xd44asxa30nv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T08:41:13Z"
    mac: ENC[AES256_GCM,data:2KLSA5hxX2Lcwqnl3lYBg7sj40hoYmCuE7jjGe02CR9xcCCkX5FmHY5+B7mPKF42Ouq2Yt3J+oR8Aqiz9PWhYXXZjnII2GSuCPM9238D3Wet94CgF30a5kn7IVpYtKkZnZvlMyIjfl0qIOSG/ATqMoVLYnh5lXFKMd9JAH9+UD8=,iv:9T/NSUUOt+uKXPt6B0LN6qJ3LXhSAhCMbQ5aAGCXGHo=,tag:n6WHv5Q+ixVGro1YU4/xfg==,type:str]
    version: 3.13.3
