apiVersion: v1
kind: Secret
metadata:
    name: redis-backend-acl
    namespace: redis
    labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: cache
        app.kubernetes.io/part-of: truehear-platform
        truehear.io/environment: staging
type: Opaque
stringData:
    users.conf: ENC[AES256_GCM,data:yIQJrukt0caA8W9I7xePxCABtC9Ye71kExvVHzFNVk0w/U6qlnSWenIjJHz0o5/UzFZGHj+fWwkX4wvQpJD93JEibIERA2bxNcQzblQ5LXxKc8+jqCsjku8TEY8MwkZnAgOZk22Bam5VV1ppzBpQWyFs4EY7RF/RwylHYeoX9AE5B5L9o/vCfpgVXXhsVxfwFvu10vLpANQ9whrhvJmJpRaTBKtywfplF16RGZBpqZ3fdMYyXnZ852VwQ1pX6B4V8G6lUDHiGlXF71YzKbUwYRcI2p885mNdj9hGDa0l7AUykYudyxQS5EJmMq2CGsM6WDYPhluTAUZBnfg9mNc32TKomCj9RW5hAk06FUI2LNIj7qi9Xg==,iv:792VxPwkNUxomU9mzFTyYIWrNA4CyAX8wPSmCEOVE6M=,tag:+PLEaXMXbmEh0Wr+rAKedA==,type:str]
    password: ENC[AES256_GCM,data:WVlReeuMQf6k/p7l1mftXe2KVOT2kWSlSC2F6n2qxDQ=,iv:OJvb8Q/Tkx/iyJLr3ng0jg0GwghIziUWZ4fsun/7ZiE=,tag:Z0sYB58NfDsOGm6/LMfQ3g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cEtaSWNCcFY5bWpXMFVF
            TzFvc3RUTENYYVk2YUcyTGJxYVVaZGtaYWhNCnp0QXJNb0h6YnRGQ21qQ1hySHRt
            RjFDYmtEd3Nja1prSUtIMU5scUJCOEkKLS0tIGdoK3o3bW5WVU1vOEpTZlVzVzZ3
            MXRLT2hhWUxsa2JIRkJFRUpvVGhXTXMKKdAdBExghLblfKZAREPdTmzRiymHlb1h
            CslYjOUOtITTb5Ek7fud63Rsuka9uJg/nUjt+utaO6GciNMiv606WA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qdn86vl3v58juv4j7gwuz3qu9hjl4fhcpvla39m848cgz3xd44asxa30nv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T15:34:32Z"
    mac: ENC[AES256_GCM,data:MRMxMhFLf73WPgGf0xfFcEVEG0bmKtEB41HrKWpIW1JmWYUycE5lIUMslAi5heRiU3pcCinB9lz5Rg+nTNCo3eDM1eroirjdE8sZHrH4fN825EqMWktOi2Xg3EKH59n70tzBenF+JDhzLMPAG3LNp3hr6Ml51eLg8AQE1p2kZr0=,iv:iMtbYDhLR1lkHzHE/aTMw84/m5OYOympNAp4rPP4X0Y=,tag:A1u1VpzASp6Ua0KTVVpzMw==,type:str]
    version: 3.13.3
