apiVersion: v1
kind: Secret
metadata:
    name: redis-auth
    namespace: redis
    labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: cache
        app.kubernetes.io/part-of: truehear-platform
        truehear.io/environment: staging
type: Opaque
stringData:
    redis-auth.conf: ENC[AES256_GCM,data:eAS3OyxcEbP1QKuYHlfq3ChlyeWLG5eA2a3uJg/PCh/0/Rh/RVJv0iZJLWlXaR2/wDmF1M4gCalm1ZhOWV4WkoxhS+gC7GwpjExnI8wXeJSdt7B/zZP2UBk=,iv:6K9yL3oAiDRNxA+PinjZ5Rit3KMGR+C3q7/YWrmSx9o=,tag:QmNwgJ+gIeRs3cvrCoYlbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVUZvVndpekwzVTJCcGpF
            UWRUc1BITmtBN09EMzFYcHVmQVpyc2JoeUI0ClVDSER2angwQllxS2daWVQvdlFD
            dVFJa201MEo2bHVPVnBwY1YrSDlWUnMKLS0tIHUvMkR5LzRneFNZbDMvdENtdytQ
            Zlo3L1A3VFdueUt2c2pJUmJwbmlXVUUK6qJmHY1uO4uwNNqp7R7xYh0F7sASVGqU
            +caKZM4odsOGwePSyS3tRiI0qqz5fvW4vwJdvf8I8bJiiWJhtobMAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qdn86vl3v58juv4j7gwuz3qu9hjl4fhcpvla39m848cgz3xd44asxa30nv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T15:34:32Z"
    mac: ENC[AES256_GCM,data:Z1sKGXLf9eFqvrDCildkkPNCabYIlGS6TBBzSIzVUgSb/rW75HalWprq/AEaPBgxmTXMkzAQioTPzfcm4itydQWWzjYYuRKWAtECl+WxCs3j/TPdYDAkW4QFzfZXrhTAIRZ+a6OA7sGah6ik2U9Nwp9K4KLYUsUjhwctozLJMxs=,iv:jGqXzrNTFZPDzAleY2HqpLzW66NzapHtQVhUTJqVWb8=,tag:YnkRwRjaoiHoOo7mcWS3+Q==,type:str]
    version: 3.13.3
