apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-configuration
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: truehear-platform
data:
  KC_HOSTNAME: https://${KEYCLOAK_HOSTNAME}
  KC_HOSTNAME_STRICT: 'true'
  KC_PROXY_HEADERS: xforwarded
