apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgresql-credentials
    namespace: keycloak
    labels:
        app.kubernetes.io/name: keycloak-postgresql
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: truehear-platform
        truehear.io/environment: staging
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:ZpHguad2Myc=,iv:up2+gQSMr+dqelmQABDQWhOrknO+0ctm158C/Gzr8gc=,tag:PSkL74D0vPv9AdSeBz21zg==,type:str]
    username: ENC[AES256_GCM,data:a/eRdoojHMg=,iv:U8lIxlfpCGdFfpm/kXZiCVeIqrfFmabEaSlV6bvO97s=,tag:nkmBg8G7uMSW4CnZOwGMCA==,type:str]
    password: ENC[AES256_GCM,data:BtnzMbF13/Wo5nq8WEGu4pdX5lveICRNZq6jNe5pC9I=,iv:iHkEw6ihOffr+r3o9YSiGlM3VXLX9CKK2kWnst+OzfE=,tag:xbNKckkwGcCyv8knGN20Fg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eXpTTC8rT2VlcjkvTlZI
            bXpuVTh1NmFWS3BsMmNlQkFmYkZGUXhGYjE0CkJXWm1sS05ISlYwT0xuWlVkNzJQ
            L1RQbmhwZE13NDZnZGdqdUptSGNuN1UKLS0tIHFsdXloT3VpcHNXNnRRQ05uS28v
            WE5nWWpQTlpxdlRUWFJWbUZmWkRHbzgKo23KODpUkkNlUAoiEH/VS3rAsKC9JtWE
            W/TkM9BVdg4n/Vol1H0uHT5/l9uOpv8MUIRxPZRX/bFoQ+cVG9dHNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qdn86vl3v58juv4j7gwuz3qu9hjl4fhcpvla39m848cgz3xd44asxa30nv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T15:34:32Z"
    mac: ENC[AES256_GCM,data:NtD4jL5gfPnk1Uh52MUenZCdLdsYC5WSVUp00+eoxQTot3m5R+XriXil5MQRS8dxA92fkf03em0BRcQ2vpJnBiD+xa5O6ZzgMY2/CJgC+RfOyITIjvR9YXJlbhi9jfZyhxV8vdl7TGO1g815/XdK1w/4KX9epC/oB8SKB175dxA=,iv:7PL7cwDYNrO6h7IpkSnMnT7pQm/kcB6g9AxRPogJAnY=,tag:cRdKWbwbK+4Cmkbesg1Nnw==,type:str]
    version: 3.13.3
