apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/keycloak
  - keycloak-configuration.yaml
  - ingress.yaml
  - keycloak-bootstrap-admin.sops.yaml
  - keycloak-postgresql-credentials.sops.yaml
  - keycloak-postgresql-tls.sops.yaml
  - keycloak-tls.sops.yaml
patches:
  - path: postgresql-storage.patch.yaml
labels:
  - pairs:
      truehear.io/environment: staging
