apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: ack-system
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:LO3t375DPJcnCMVcmDEGQwd6yOwOcUlp9l1R8qQ8tS6q6jdXwxFGZi4zCwakvpREb2bUUDpJd9UM1a7PN3mo4o4pC5Y621Y4LMRiYHuCwi6nh68gpG4FzA0a1Y8cBODMwZIeKcTFY+ai4lAfV8+nblR6ktZgXTARup2iZbwcgNDggKPnNvgd,iv:zgZquTw1cdhPkxrK+kBP9qyyQdwJrpVQoyGiYqgY9a4=,tag:XEq5hihFWShjGfHmVNiWLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SDJuUk5FaDJtUnowZ1hJ
            aS9HTGVnWnlZUHdmQ0VLeVJRU3g4Uk5qWWhNCmJjcTNtN2o3bmRYMFUzNEhWcGM3
            M0xVZlh6bFY2dkZFOGk3T1FBR1FFbVUKLS0tIHMzdWpzK2pmYmVFSFl4ZGhZOUtv
            djdmZERaZFpYK2ViYTFQM04vSGN2TkUKpSpxdtYIJK+NEkGfle3BeoXo3ms0BHoy
            ow6u9OLA8anUukF5ojE/Ahrzm3i9Idy/dBvqhm6vP1XnEijoRwZsGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qdn86vl3v58juv4j7gwuz3qu9hjl4fhcpvla39m848cgz3xd44asxa30nv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-03T12:24:08Z"
    mac: ENC[AES256_GCM,data:2/bWlER9WHqmcQG/XeT1zYBB5UpjrUb6D3wfIoIM1xtjWK3utzcgodZtH/8WhBWf8jTEMRqYeDWhgopgbJItdsKPpDH3hTaMm3xKs3w3nJgYUpV7br8xvW6kdAwdg+DkzxEurUoTXye61x3u7mZJRKfV7cPUWrD8mB03DFYsZWM=,iv:TTly/yVBuw9bguiwqAcHWw1/F4zG++KhfGkmaUH9unM=,tag:JopmVbRgz5qsciUJ4b9tSw==,type:str]
    version: 3.13.1
