apiVersion: v1
kind: Secret
metadata:
    name: aws-credentials
    namespace: ack-system
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:p5EiqC1bDb6ldMDxV+PsJMCaV97zaAcZNuOgRF2jk2ogd2h2926FtBwFn9i8dR+AsYiMkgwSKykZO8eH20vpS8XvqDa3gkFHWxslewdUWKjETjtw/zmlIBSSTL+e4VHQJDTaJAUc98QNdMtp9zEMUCuPpqacXHI6VPbolxcHjSgL9RBy8n53,iv:ca1dCuxet3cVL6eOaeLb9MBDnJV+heYHW/Lm2SMlB0w=,tag:7jcDAmWXb8MGUVgGlsLQOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMFNiM3FoMnRpT2tMd3hs
            NTQyaTBpUVdKNmR4Y0wrSVRBOFYyUTZlSDBNCjZHcjc2N3Q0SndreUdjVW4vL25C
            ZVpoT3doaWllMnlvWlQ2QVRVNlB2c0EKLS0tIEtNTmNCUFpEcnIyYnROUFpNUFRY
            RTQrUjFXOUYzUTBlNmVYY1J2MFRLK2MKdVwHynfL/wO7UWla8vs5Q4dco+vebkEd
            2r88gtbeRxtQXPbvMFZOxX1IHEN7cseY7bMpAavxwxW+r8OPg9HR6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qdn86vl3v58juv4j7gwuz3qu9hjl4fhcpvla39m848cgz3xd44asxa30nv
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T08:41:13Z"
    mac: ENC[AES256_GCM,data:LzopNbF+NEFAKy2ViQNnj1laq5jxnIcJbR3LDOFHQe2FHXJ5WKLT46MQMKXH/wB3TxN+YexzjSOz047Z0MDE5S5dUWzZu+f4MnRcytZ2BeATgx6UtqukYKJ541bv2RkQyz2FIrlsc5/bqo4Dvu5wT9yosg/VQ5seZEnFVz38HmM=,iv:n6CfkUHwclZLFvs9Zup3Wil7GlWfvr57BrevUwTa/38=,tag:SW31QmYYL8WSXquA/LPNfA==,type:str]
    version: 3.13.3
