apiVersion: v1
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFuzCCA6OgAwIBAgIUKEsIled5sJXy2w56PaZymEJZA0wwDQYJKoZIhvcNAQEL
    BQAwXjELMAkGA1UEBhMCRkkxETAPBgNVBAoTCFRydWVIZWFyMRMwEQYDVQQLEwpQ
    S0kgQXBwIFYyMScwJQYDVQQDDB5UcnVlSGVhciBQS0kgQXBwIFYyIFJvb3QgQ0Hi
    gIswHhcNMjYwOTE0MDgzMjQxWhcNMzYwOTExMDgzMjQxWjBpMQswCQYDVQQGEwJG
    STERMA8GA1UEChMIVHJ1ZUhlYXIxEzARBgNVBAsTClBLSSBBcHAgVjIxMjAwBgNV
    BAMMKeKAi1RydWVIZWFyIFBLSSBBcHAgVjIgSW50ZXJtZWRpYXRlIENB4oCLMIIC
    IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA+dIMx/QCQJXMqGlfpC3u2z32
    sF7ytW3Farb/mJi+mRSXDMGVrmLohX16tM4saXF+qlmPobDeCXWGQaesxHLthzr3
    kWkPiZJFmv58o+05JSJA9103anZabZpA4j2vFx6ocEMecFT0L+FFakiF7o5PrBWF
    rQPuhpkUbSc2brvpZuRDBX5qafyWAouUlry2XAkS1aR7YkYIVgZScezKALSgz0NM
    BCwRq/tA9uI+YAweJlRaSMhwVU8Y6SyVnQdolmU4v0SNiWqvq5mBWdPRIQq2Ps9Y
    2zHW/b3uSvF1yi+coay6W38Dlx197xwNqvZshpumV6hwq0kBamksjtqeM5mNtQvy
    VemGVVR+EQ9Od003SjDc6n6QGiPCj+X+rBHRvd8es0MO6h59SWXFr59e13HJaJMD
    cWplq8YtJBJypECcqu4OnpynEmQu3DvTrsBFANgJ0yODwzVVvd6dAOJSC5mHZUv0
    FykxQs3IkprH4B/70kX9krmk5NKzYkkXC7WYkaVS/ajJyERI522/TopZREqLegNw
    RGf//MjNHAFXxFzPeUbmxjEuyVpydK14NaafAByFQyvajSM8+Hju5wumllGkR41L
    MREkSaVmZRPNZr6qh0wx08Nm0FcL+88JODZcNBYBZ0hRZ9U15waETVHUR4DPpDHl
    p5ImBMkezVx5evUeaGsCAwEAAaNmMGQwEgYDVR0TAQH/BAgwBgEB/wIBADAOBgNV
    HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFJqJQXDf6VnUmiERbE5IIzfc7e0XMB8GA1Ud
    IwQYMBaAFCPa8nxcyT36Hr2/lzFVrQHP71HPMA0GCSqGSIb3DQEBCwUAA4ICAQA6
    3Ofc9ljOolgg7V2xqzDC5SHnLQC8zo5lCiK5grqVhVhpbDtBlWo3Nh2VwMBKoVe9
    XUkvsRPOtXyD0e2qVl2lMbaaDiRAXG7U3q5Zu6bOjESnLmieTMG8ObHNneQUZRW8
    wOxICrqq3GESiVDeKp4RCQNIGtM39JQMkqZeqwOO+46NyJgyhfeqzGtYSOqNfQuj
    wFAy/9cGT2JcX1cxioSjEUeJ1i+YIJw8rxTYpObSc8j42qIUHH/1PRObTeVDcctt
    shP8atoEP6zYKdHwLDNMEsTyozpU3VJbhjSMChzXJxLx6zRWqBlUal8e3Ig2xeUy
    px9HFkd5x94S+VTplZZXxCy5443xVcjmAI2YgpHUnZhajLdTAwIa8ifRV24lhuAX
    hjHs2J5sG6inDXLq8FoUDBhy8miSGAcQjEbMceS5OjVBBKaSIMCWjRWRYjgdXYtC
    YELoyrMKk5ku9VB/HepRo4A6BPQgYwsTIwGBCW1MY7xYI4KCQvSyGGdZC98zMEqj
    YX9GbZ1H27gCyVkU1w9gI3vY36q/RWL3y52Q0M6aLlXkVvJ9FAJQLs/8bXnzsYB0
    AGEV08fEmZ/95hACVZ9KpuyXBKwEOXrZ+DSLG/WBw6oHzwfC2P2XGIRrlPw44vvw
    cdEhgSxDfVTRQwnLIO9A3q0QCs5vRd74Ssvc2Vqfvw==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFsDCCA5igAwIBAgIUAyuUch8VmdAkSKOUfei7KXuQjrkwDQYJKoZIhvcNAQEL
    BQAwXjELMAkGA1UEBhMCRkkxETAPBgNVBAoTCFRydWVIZWFyMRMwEQYDVQQLEwpQ
    S0kgQXBwIFYyMScwJQYDVQQDDB5UcnVlSGVhciBQS0kgQXBwIFYyIFJvb3QgQ0Hi
    gIswHhcNMjYwOTE0MDgyODU0WhcNNDYwOTA5MDgyODU0WjBeMQswCQYDVQQGEwJG
    STERMA8GA1UEChMIVHJ1ZUhlYXIxEzARBgNVBAsTClBLSSBBcHAgVjIxJzAlBgNV
    BAMMHlRydWVIZWFyIFBLSSBBcHAgVjIgUm9vdCBDQeKAizCCAiIwDQYJKoZIhvcN
    AQEBBQADggIPADCCAgoCggIBAMlEBx+xfaJslDEzgGIm7qn94dB6PvIBZATNrHSX
    bUivANaAoF0Xpqai4SVeVwqfv2XRN54PNBcccK06s3nZrCyYqszqb4Ewkfo9ZPs+
    X9XKHCzzdGmgeftownbJ4+EF0HJvg2e1OEpo7UHlh987emsWK5SfcqpLousioACU
    Zq24I/BkUlHRcP+N3JNKYYT/Bnb42ZUcJE1AGjoP6yqrLFpSSvnIEy+TjhnT4uFm
    TRgNDGTXqFLS61YCEZ59GiHWZdkqf54B+rgztFcsyzh6MuTwAzKAdJb8AFI+xg/u
    OKjsiFS/urUiUUeo1SgdOLwSHfpZLlfr07NmJ5ldMSS59xDjYASQZMV/75It4TuC
    x50RGwlEzNYIFfEsD5aytXxEMKNjOmaX4hkiUkAgONhIhDSX75l243hAv8x11ZLU
    /efPUnwEFFyJqp81GJ8CndWskk31RhfcxX+pkdrRX06gZasvGEabdizGQbFOw9bb
    RXudsPXWAnjdc7ZfI+DiIQWtFXgnP+HMuE4jmgLrZfBEhk0YdxT5nb6lDreyOY87
    nY54/tymg5aemTM5cv+5naeFLERe5yYggWs4+/MEB2rxt5yJ7EIoRg4Tvodap2nT
    /RTQRVRsoreOSbfspk2DlFVWOaFBTgDh1gQg2h59M2Uu2KSZxH5/U0oz6GLKIHlP
    wQIPAgMBAAGjZjBkMBIGA1UdEwEB/wQIMAYBAf8CAQEwDgYDVR0PAQH/BAQDAgEG
    MB0GA1UdDgQWBBQj2vJ8XMk9+h69v5cxVa0Bz+9RzzAfBgNVHSMEGDAWgBQj2vJ8
    XMk9+h69v5cxVa0Bz+9RzzANBgkqhkiG9w0BAQsFAAOCAgEAV5kfvHh2vSvV7l39
    NsRE616fSOKFNqvTJW7ICLZz3XjeNUWGj9h3+L1Kic8b937aQGoANlDEfodv/EsH
    r/nKoM/FIa9z6kxqCI75m5vuL9ELwgoG97EVC0LfAplXCv6viBOhFa9HV7a3ZhqG
    3lzbeSdQ5SRR2lXcGi2OE7iX2TPgTcY5sAfHjRbNDXUPLWSvcUq38kYELcLLzEB0
    C9B7CsbnmkYAL9rL+REZPxGMBjR0N3HqHMyYt4Cvo2/5OJug3F/kGR/vL2wL5LUY
    QXpZWP4eObWIUF+b343hkNjUOYGj5peUBXvgn0cfsODhk18IADK9kEVtpDTrp/wk
    Kwk8Auld1cTbsPInkDPKSaQ8dp1AeW3ysb2vbc2U6gVqCjCuYYhaeu7Iz92ASYBE
    9w6TPRfyEVGuQll8xwJ/q1vKjjeT/skivRYAwfWz4yJtgP4ggZpce20bgsfy7+22
    cHy/8faQmBajLO/LEuU/bqnBsRElmazNQ65Z4IhDn8DxkUYlCenrB2nAEaPJX12N
    13pJ90A0Jl0r3lyyJsiBTcszvO7GI+UkCAF2mcjhF9/PAl6UiZRKvRMHBYfZVitA
    n2Gni7i1+alyFl1BYVtEl6sgDVsQAi6YudtM1V9BiuCJ+DbOHJQXp83KELaO3rfo
    F7SPGPmfj/P2TwU0GiIzvy5aepg=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: truehear-ca-bundle
  namespace: backend
