apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HGpXI39ouFc8Ox8DswWvOT6GgFq68BXBsKSHJkT8IthvSg4JN2jUbElS6vbUq4WmEtDjc5EXmvA9nIKtXtdUx3B1XEghY7zXJ0ISGt6KAYEu3wdLwyYyKLqaELa+0NHGH4UlH7YjHfIXhfxPY2vNpjahxQEiGuaYxGtllIY+0HESWUiXKCbcCFP7Wu9BJUq1TdEnXavY2j8T0eEwNma6+XQjYOCmhjw39QjDr3hu9uHe9s7GCxNVnfyp0MRU9IZPsIM7qKVXNxP2Kl93KfGiGOdtppwRj0/9ecZCB7f1uUFT9YS4Yod7xOFrILU7KKCwwzOPKuc7pk9qzKgxls6zUHyfWNseVT/kdV+eGuyy2gM68tlwkVWWSkEou46ElZIrU3hrC8a+JjXzoQvEoB4lig==,iv:+tuDOIhSyDnTvqkHLQ734Z+45fnk3ZvK2rx3TXETzes=,tag:uxEC7sLVd1Ddyp6I8ms9HQ==,type:str]
kind: Secret
metadata:
    name: ghcr-credentials
    namespace: backend
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTnhwcU8xNHE3bHFEYUxF
            alF0aG1Nb3I4Sy9aTHg4dUFRL0FtMnpzNzE4CkFaQjFHbmRCcmE3K1Bid1RNeWRC
            MVpPOUNTK0JNTDVTaS81bVZWdWZncGsKLS0tIHZ0TENrL285TmVTZHRTdmsxUTdm
            N0Qvbm5lcE93UnlFNWJ3MGhCQzQ2eWcKEHb1/GRvJmxLvm5b3HVOyAHqSGqF2jLE
            2Qjme3Fu6mLoezgNr0hh4LWotwQ6ftcTy50f3lVDqHBiIPIqGdrBsA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rnpytnyvs6r8wcf740tp47wjkcqap6szqnapewuhw3vnytelvcvqwgmv0h
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T07:00:44Z"
    mac: ENC[AES256_GCM,data:MkH40WHXKy7M/XXc/lsc5+fL9Ou8CdFOJmoRxvLAT2nktEnwmjsBlnQWF6rYsUKZkTBjgjPg3rOMatVNpHqwBQJ7yiV+JZqS5XCFqbprJjaHNa3OXth+6wRYQSQXGftH0K9lcqysPuqs/aRhGyG0VcYeYDub8L2MB75vlkDvAXc=,iv:p1RCKXigaMf7Vvp6EOv93hvgBmEbZxomTICctlxtXdc=,tag:vKaansaxtzG8jMWf0fxBbg==,type:str]
    version: 3.13.3
