apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - ghcr-credentials.sops.yaml
  - ca-bundle.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
