apiVersion: v1
kind: Secret
metadata:
    name: keycloak-postgresql-credentials
    namespace: keycloak
    labels:
        app.kubernetes.io/name: keycloak-postgresql
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: truehear-platform
type: Opaque
stringData:
    database: ENC[AES256_GCM,data:irxS1Z4JFks=,iv:bw2Tyn2/Uf/eABPaOaHtvg+fXOAnsnaRSxvgVllc16M=,tag:sBhVcVsR1MVDlHDKsJwAew==,type:str]
    username: ENC[AES256_GCM,data:EQ8wt39FfFU=,iv:lL27VKXeYPPZDSSeXS5h7CeV7J9B4mvqBBEUDAarU0c=,tag:78Ils4JP9aOATgpxczavTA==,type:str]
    password: ENC[AES256_GCM,data:Lo6M6eneSTlNaGHiIeuqwgBtOVZzOfGazsAgfChXvNc=,iv:oshdz/lmSXhIYQ4rszv26Y8ikNeTnSe9/lTlA33AS2s=,tag:/tb5biWuE1snGiIB1EIeig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvV2NiU2M1d2V6bDFvUEVx
            TUtqbkU1SXU5TXV5UUUzdmpsVUl5WUJjSVgwCnVsRDdqMmNxUDBYd3BVYnhPbVZK
            U25MUmlsbjRsMTRuMiszRmNBR1hJUnMKLS0tIHFHSzBhbVdCNTQxQk1yZEpyOGpY
            c2Jpby9ReE1DeHU1Y3plTi9MdUIxY1kKDFCvgT/NNScynevk5NRlDZoijejUbL0E
            INU16sm9d5VN8jgaIwwr+xNx24ohnyQp2Ty2GHYgGEjZIT44G80fjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1amqtgevmdxutg07rkr3wggua43620zgncgfq53vkww0283wrgspqv9q0jw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T09:43:22Z"
    mac: ENC[AES256_GCM,data:+XZ0+J7VnjV/MkC0WZy3gIpBYO0TbJuf8qAmajQ6T7vywVKrNScznMz8VbPbwcCBFVAtRBhB9FmHpBkMhAYC1HE4WsrCaXX6sM3hw8kPRVk6o2/SDKp7LHIE53sR9tNg6XdJ/a454hdR2XBheETcPund8+1W7E4NacywDELcg6Q=,iv:I8A1XGJuaJJGTxDzo/rtohwX7Y3BB7t8ORJrrYvBUEs=,tag:jn96SeRsXcmFsbHszEODwA==,type:str]
    version: 3.13.3
