apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-postgresql
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak-postgresql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: truehear-platform
automountServiceAccountToken: false
