apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Root reconciled by the FluxInstance running on the local CAPD workload
# cluster.
resources:
  - podinfo
  - vault/flux-ks.yaml
  - backend/flux-ks.yaml
  - rabbitmq/flux-ks.yaml
  - redis/flux-ks.yaml
