apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm.yaml
  - vault-tls.sops.yaml
configMapGenerator:
  - name: vault-values
    namespace: vault
    files:
      - values.yaml=values.yaml
    options:
      disableNameSuffixHash: true
labels:
  - pairs:
      truehear.io/environment: staging
