apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
    app.kubernetes.io/part-of: truehear-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
